### ISSUE TITLE
Comprehension Measurement Widget Improvements 

### ISSUE THREAD

**Issue by DevSchmidtchen** [hpi-dhc/comprehension-measurement#22]
## Tasks

- [x] Improve design
- [x] Implement `times_selected`
- [x] Move button to the right
- [x] Close after last page
- [x] Require answers (converted to issue #23)
